### ISSUE TITLE
Filter season 2020

### ISSUE THREAD

**Issue by Way-Dev** [jasparagus/LoLlyPlotty#85] opened 2020-11-03 15:19 UTC
Hello, the filter season 2020 doesn't work.

It displays 0 when I have played games.

![image](https://user-images.githubusercontent.com/43731977/98004462-4318fe00-1df0-11eb-9293-e7fe27c53354.png)

Thank you ! 👍

**Comment by jasparagus** [comment] 2020-11-03 16:11
Hi Way-Dev! The cause is that I had hard-coded the seasons (and other game constants), and hadn't updated anything since 2019 (sorry). Since then, Riot has added this: https://developer.riotgames.com/docs/lol#general_game-constants, so I had planned to rebuild that little portion using their static info and just never got around to it.

I honestly didn't realize anyone besides me used this haha. Let me fire it back up and see how much work it is to rebuild with the new static info; it shouldn't be too hard.

**Comment by Way-Dev** [comment] 2020-11-03 16:40
Yes it's really interesting, I'm currently studying the league of legend stats and looking at what's already been done.

Thank you very much!

**Comment by jasparagus** [comment] 2020-11-03 17:11
![image](https://user-images.githubusercontent.com/12389821/98017767-8eadb680-1db4-11eb-9899-f546bb67773e.png)

Are you seeing this when you run it with your API key? It seems to be finding my recent matches OK.

**Comment by jasparagus** [comment] 2020-11-03 17:14
Also, after checking riot's static API for seasons (http://static.developer.riotgames.com/docs/lol/seasons.json), it looks like they never included Season 2020 in there because they deprecated "Season" according to their API:
![image](https://user-images.githubusercontent.com/12389821/98018058-f5cb6b00-1db4-11eb-8bfd-3f9931bfea87.png)

**Comment by Way-Dev** [comment] 2020-11-03 17:38
Yes, download correctly work and I have access to the statistics of recent games.

Ah yes, I understand better now.

**Comment by jasparagus** [comment] 2020-11-30 19:46
Going to close this issue since it ended up being deprecated (by Riot). I may remove the "season" filter and just replace it with a "time" slider or something.

**Closed by jasparagus** 2020-11-30 19:46 UTC
